-- Diagnósticos pediátricos por especialidade (versão compacta). SEGURO: só INSERT, pula o que já existe.
-- Insere em Principal e Secundário. Rode tudo de uma vez.
INSERT INTO public.pergunta_opcoes_diagnostico (pergunta_id, codigo, label, has_input, ordem, categoria)
SELECT p.id, p.prefixo || '_PED_' || v.n, v.label, false, 5000 + v.n, v.categoria
FROM (VALUES
(1,'Anemia ferropriva','Hematológico / Oncológico'),
(2,'Anemia megaloblástica por deficiência de vitamina B12 ou folato','Hematológico / Oncológico'),
(3,'Anemia da doença crônica/inflamatória','Hematológico / Oncológico'),
(4,'Anemia hemolítica autoimune','Hematológico / Oncológico'),
(5,'Doença falciforme','Hematológico / Oncológico'),
(6,'Talassemias','Hematológico / Oncológico'),
(7,'Esferocitose hereditária','Hematológico / Oncológico'),
(8,'Deficiência de glicose-6-fosfato desidrogenase (G6PD)','Hematológico / Oncológico'),
(9,'Anemia aplástica','Hematológico / Oncológico'),
(10,'Aplasia pura da série vermelha','Hematológico / Oncológico'),
(11,'Anemia de Diamond-Blackfan','Hematológico / Oncológico'),
(12,'Púrpura trombocitopênica imune (PTI)','Hematológico / Oncológico'),
(13,'Hemofilia A e B','Hematológico / Oncológico'),
(14,'Doença de von Willebrand','Hematológico / Oncológico'),
(15,'Deficiências congênitas de fatores da coagulação','Hematológico / Oncológico'),
(16,'Coagulação intravascular disseminada (CIVD)','Hematológico / Oncológico'),
(17,'Trombocitopenia neonatal','Hematológico / Oncológico'),
(18,'Trombofilias hereditárias e adquiridas','Hematológico / Oncológico'),
(19,'Trombose venosa associada a cateter','Hematológico / Oncológico'),
(20,'Neutropenias transitória, autoimune ou congênita','Hematológico / Oncológico'),
(21,'Agranulocitose','Hematológico / Oncológico'),
(22,'Pancitopenia','Hematológico / Oncológico'),
(23,'Síndromes de falência medular','Hematológico / Oncológico'),
(24,'Síndrome hemofagocítica/linfo-histiocitose hemofagocítica','Hematológico / Oncológico'),
(25,'Síndromes mielodisplásicas','Hematológico / Oncológico'),
(26,'Hiperesplenismo','Hematológico / Oncológico'),
(27,'Leucemia linfoblástica aguda','Hematológico / Oncológico'),
(28,'Leucemia mieloide aguda','Hematológico / Oncológico'),
(29,'Leucemia mieloide crônica','Hematológico / Oncológico'),
(30,'Linfoma de Hodgkin','Hematológico / Oncológico'),
(31,'Linfomas não Hodgkin','Hematológico / Oncológico'),
(32,'Artrite idiopática juvenil','Reumatológico'),
(33,'Lúpus eritematoso sistêmico juvenil','Reumatológico'),
(34,'Dermatomiosite juvenil','Reumatológico'),
(35,'Esclerose sistêmica','Reumatológico'),
(36,'Esclerodermia localizada/morfeia','Reumatológico'),
(37,'Doença mista do tecido conjuntivo','Reumatológico'),
(38,'Síndrome de Sjögren juvenil','Reumatológico'),
(39,'Síndromes de sobreposição','Reumatológico'),
(40,'Vasculite por IgA (púrpura de Henoch-Schönlein)','Reumatológico'),
(41,'Doença de Kawasaki','Reumatológico'),
(42,'Arterite de Takayasu','Reumatológico'),
(43,'Poliarterite nodosa','Reumatológico'),
(44,'Granulomatose com poliangiite','Reumatológico'),
(45,'Poliangiite microscópica','Reumatológico'),
(46,'Vasculites associadas ao ANCA','Reumatológico'),
(47,'Febre familiar do Mediterrâneo','Reumatológico'),
(48,'Síndrome PFAPA','Reumatológico'),
(49,'Síndromes periódicas associadas à criopirina','Reumatológico'),
(50,'Síndrome de ativação macrofágica','Reumatológico'),
(51,'Artrite reativa','Reumatológico'),
(52,'Febre reumática','Reumatológico'),
(53,'Síndrome antifosfolípide','Reumatológico'),
(54,'Uveíte associada às doenças reumatológicas','Reumatológico'),
(55,'Dor musculoesquelética amplificada','Reumatológico'),
(56,'Fibromialgia juvenil','Reumatológico'),
(57,'Hipermobilidade articular e síndrome de Ehlers-Danlos','Reumatológico'),
(58,'Osteomielite crônica não bacteriana/CRMO','Reumatológico'),
(59,'Doença do refluxo gastroesofágico','Gastrointestinal / Hepático'),
(60,'Esofagite eosinofílica','Gastrointestinal / Hepático'),
(61,'Gastrite e doença ulcerosa péptica','Gastrointestinal / Hepático'),
(62,'Infecção por Helicobacter pylori','Gastrointestinal / Hepático'),
(63,'Acalasia','Gastrointestinal / Hepático'),
(64,'Estenoses esofágicas','Gastrointestinal / Hepático'),
(65,'Ingestão de corpo estranho ou substância cáustica','Gastrointestinal / Hepático'),
(66,'Distúrbios da deglutição','Gastrointestinal / Hepático'),
(67,'Constipação intestinal funcional','Gastrointestinal / Hepático'),
(68,'Diarreia aguda, persistente ou crônica','Gastrointestinal / Hepático'),
(69,'Alergia à proteína do leite de vaca','Gastrointestinal / Hepático'),
(70,'Intolerância à lactose','Gastrointestinal / Hepático'),
(71,'Doença celíaca','Gastrointestinal / Hepático'),
(72,'Doença de Crohn','Gastrointestinal / Hepático'),
(73,'Retocolite ulcerativa','Gastrointestinal / Hepático'),
(74,'Doença inflamatória intestinal não classificada','Gastrointestinal / Hepático'),
(75,'Síndrome do intestino irritável','Gastrointestinal / Hepático'),
(76,'Dor abdominal funcional','Gastrointestinal / Hepático'),
(77,'Invaginação intestinal','Gastrointestinal / Hepático'),
(78,'Divertículo de Meckel','Gastrointestinal / Hepático'),
(79,'Pólipos e poliposes hereditárias','Gastrointestinal / Hepático'),
(80,'Síndrome do intestino curto','Gastrointestinal / Hepático'),
(81,'Linfangiectasia intestinal','Gastrointestinal / Hepático'),
(82,'Enteropatia perdedora de proteínas','Gastrointestinal / Hepático'),
(83,'Distúrbios da motilidade intestinal','Gastrointestinal / Hepático'),
(84,'Hepatites virais, autoimunes e metabólicas','Gastrointestinal / Hepático'),
(85,'Colestase neonatal','Gastrointestinal / Hepático'),
(86,'Atresia de vias biliares','Gastrointestinal / Hepático'),
(87,'Deficiência de alfa-1-antitripsina','Gastrointestinal / Hepático'),
(88,'Doença de Wilson','Gastrointestinal / Hepático'),
(89,'Esteatose hepática associada à disfunção metabólica','Gastrointestinal / Hepático'),
(90,'Insuficiência hepática aguda','Gastrointestinal / Hepático'),
(91,'Cirrose e hipertensão portal','Gastrointestinal / Hepático'),
(92,'Trombose da veia porta','Gastrointestinal / Hepático'),
(93,'Colelitíase e coledocolitíase','Gastrointestinal / Hepático'),
(94,'Colangite esclerosante primária','Gastrointestinal / Hepático'),
(95,'Pancreatite aguda, recorrente ou crônica','Gastrointestinal / Hepático'),
(96,'Insuficiência pancreática exócrina','Gastrointestinal / Hepático'),
(97,'Fibrose cística com comprometimento digestivo','Gastrointestinal / Hepático'),
(98,'Síndrome nefrótica','Renal'),
(99,'Síndrome nefrítica','Renal'),
(100,'Glomerulonefrite pós-infecciosa','Renal'),
(101,'Nefropatia por IgA','Renal'),
(102,'Nefrite lúpica','Renal'),
(103,'Glomerulonefrite membranoproliferativa','Renal'),
(104,'Glomerulonefrite rapidamente progressiva','Renal'),
(105,'Síndrome de Alport','Renal'),
(106,'Doença de lesões mínimas','Renal'),
(107,'Glomeruloesclerose segmentar e focal','Renal'),
(108,'Lesão renal aguda','Renal'),
(109,'Doença renal crônica','Renal'),
(110,'Nefrite intersticial aguda','Renal'),
(111,'Necrose tubular aguda','Renal'),
(112,'Nefrotoxicidade medicamentosa','Renal'),
(113,'Síndrome hemolítico-urêmica','Renal'),
(114,'Distúrbios hidroeletrolíticos e acidobásicos','Renal'),
(115,'Acidose tubular renal','Renal'),
(116,'Síndrome de Bartter','Renal'),
(117,'Síndrome de Gitelman','Renal'),
(118,'Diabetes insípido nefrogênico','Renal'),
(119,'Síndrome de Fanconi','Renal'),
(120,'Infecção do trato urinário','Renal'),
(121,'Pielonefrite','Renal'),
(122,'Refluxo vesicoureteral','Renal'),
(123,'Hidronefrose','Renal'),
(124,'Obstrução da junção ureteropélvica','Renal'),
(125,'Válvula de uretra posterior','Renal'),
(126,'Megaureter','Renal'),
(127,'Bexiga neurogênica','Renal'),
(128,'Disfunção miccional e enurese','Renal'),
(129,'Rim multicístico displásico','Renal'),
(130,'Doença renal policística','Renal'),
(131,'Hipoplasia ou displasia renal','Renal'),
(132,'Anomalias congênitas dos rins e trato urinário (CAKUT)','Renal'),
(133,'Hipertensão arterial sistêmica','Renal'),
(134,'Hematúria e proteinúria','Renal'),
(135,'Litíase urinária','Renal'),
(136,'Hipercalciúria','Renal'),
(137,'Nefrocalcinose','Renal'),
(138,'Infecções de vias aéreas superiores','Infeccioso / Séptico'),
(139,'Otite média aguda','Infeccioso / Séptico'),
(140,'Sinusite bacteriana','Infeccioso / Séptico'),
(141,'Faringoamigdalite','Infeccioso / Séptico'),
(142,'Bronquiolite viral aguda','Infeccioso / Séptico'),
(143,'Pneumonia adquirida na comunidade','Infeccioso / Séptico'),
(144,'Pneumonia hospitalar ou associada à ventilação mecânica','Infeccioso / Séptico'),
(145,'Tuberculose','Infeccioso / Séptico'),
(146,'Influenza','Infeccioso / Séptico'),
(147,'COVID-19','Infeccioso / Séptico'),
(148,'Coqueluche','Infeccioso / Séptico'),
(149,'Sepse e choque séptico','Infeccioso / Séptico'),
(150,'Infecções associadas à assistência à saúde','Infeccioso / Séptico'),
(151,'Meningite bacteriana, viral ou fúngica','Infeccioso / Séptico'),
(152,'Encefalite e meningoencefalite','Infeccioso / Séptico'),
(153,'Abscesso cerebral','Infeccioso / Séptico'),
(154,'Neurotuberculose','Infeccioso / Séptico'),
(155,'Endocardite infecciosa','Infeccioso / Séptico'),
(156,'Miocardite e pericardite infecciosas','Infeccioso / Séptico'),
(157,'Impetigo, celulite e erisipela','Infeccioso / Séptico'),
(158,'Abscessos cutâneos','Infeccioso / Séptico'),
(159,'Síndrome da pele escaldada estafilocócica','Infeccioso / Séptico'),
(160,'Osteomielite','Infeccioso / Séptico'),
(161,'Artrite séptica','Infeccioso / Séptico'),
(162,'Piomiosite','Infeccioso / Séptico'),
(163,'Dengue','Infeccioso / Séptico'),
(164,'Chikungunya','Infeccioso / Séptico'),
(165,'Zika','Infeccioso / Séptico'),
(166,'Malária','Infeccioso / Séptico'),
(167,'Leishmaniose visceral e tegumentar','Infeccioso / Séptico'),
(168,'Doença de Chagas','Infeccioso / Séptico'),
(169,'Febre amarela','Infeccioso / Séptico'),
(170,'Leptospirose','Infeccioso / Séptico'),
(171,'Riquetsioses','Infeccioso / Séptico'),
(172,'Sífilis congênita','Infeccioso / Séptico'),
(173,'Toxoplasmose congênita','Infeccioso / Séptico'),
(174,'Citomegalovirose congênita','Infeccioso / Séptico'),
(175,'Rubéola congênita','Infeccioso / Séptico'),
(176,'Herpes neonatal','Infeccioso / Séptico'),
(177,'HIV perinatal','Infeccioso / Séptico'),
(178,'Hepatites B e C perinatais','Infeccioso / Séptico'),
(179,'Sepse neonatal precoce ou tardia','Infeccioso / Séptico'),
(180,'Infecção pelo HIV','Infeccioso / Séptico'),
(181,'Infecções oportunistas','Infeccioso / Séptico'),
(182,'Infecções em imunodeficientes, transplantados ou neutropênicos','Infeccioso / Séptico'),
(183,'Infecções relacionadas a cateter','Infeccioso / Séptico'),
(184,'Infecções por bactérias multirresistentes','Infeccioso / Séptico'),
(185,'Infecções fúngicas invasivas','Infeccioso / Séptico'),
(186,'Febre de origem indeterminada','Infeccioso / Séptico'),
(187,'Laringite viral/crupe','Respiratório'),
(188,'Epiglotite','Respiratório'),
(189,'Traqueíte bacteriana','Respiratório'),
(190,'Laringomalácia e traqueomalácia','Respiratório'),
(191,'Estenose subglótica','Respiratório'),
(192,'Paralisia de cordas vocais','Respiratório'),
(193,'Obstrução por corpo estranho','Respiratório'),
(194,'Abscesso retrofaríngeo ou peritonsilar','Respiratório'),
(195,'Angioedema com comprometimento da via aérea','Respiratório'),
(196,'Papilomatose respiratória recorrente','Respiratório'),
(197,'Asma','Respiratório'),
(198,'Estado de mal asmático','Respiratório'),
(199,'Sibilância recorrente do lactente','Respiratório'),
(200,'Pneumonia comunitária ou hospitalar','Respiratório'),
(201,'Pneumonia aspirativa','Respiratório'),
(202,'Pneumonia grave ou necrosante','Respiratório'),
(203,'Derrame pleural parapneumônico','Respiratório'),
(204,'Empiema pleural','Respiratório'),
(205,'Abscesso pulmonar','Respiratório'),
(206,'Pneumatocele','Respiratório'),
(207,'Atelectasia','Respiratório'),
(208,'Bronquiectasias','Respiratório'),
(209,'Tuberculose pulmonar','Respiratório'),
(210,'Hemorragia pulmonar/hemoptise','Respiratório'),
(211,'Doença pulmonar intersticial','Respiratório'),
(212,'Fibrose pulmonar','Respiratório'),
(213,'Bronquiolite obliterante','Respiratório'),
(214,'Discinesia ciliar primária','Respiratório'),
(215,'Fibrose cística','Respiratório'),
(216,'Displasia broncopulmonar','Respiratório'),
(217,'Hipertensão pulmonar','Respiratório'),
(218,'Apneia obstrutiva do sono','Respiratório'),
(219,'Insuficiência respiratória aguda hipoxêmica','Respiratório'),
(220,'Insuficiência respiratória aguda hipercápnica','Respiratório'),
(221,'Síndrome do desconforto respiratório agudo pediátrico (PARDS)','Respiratório'),
(222,'Pneumotórax simples ou hipertensivo','Respiratório'),
(223,'Hemotórax','Respiratório'),
(224,'Quilotórax','Respiratório'),
(225,'Fístula broncopleural e escape aéreo persistente','Respiratório'),
(226,'Pneumomediastino','Respiratório'),
(227,'Edema agudo de pulmão','Respiratório'),
(228,'Síndrome de aspiração pulmonar','Respiratório'),
(229,'Hemorragia alveolar difusa','Respiratório'),
(230,'Lesão pulmonar associada à ventilação mecânica','Respiratório'),
(231,'Falha de extubação','Respiratório'),
(232,'Obstrução de cânula de traqueostomia','Respiratório'),
(233,'Dependência de ventilação mecânica','Respiratório'),
(234,'Comunicação interatrial','Cardiovascular'),
(235,'Comunicação interventricular','Cardiovascular'),
(236,'Persistência do canal arterial','Cardiovascular'),
(237,'Defeito do septo atrioventricular','Cardiovascular'),
(238,'Coarctação da aorta','Cardiovascular'),
(239,'Estenose aórtica','Cardiovascular'),
(240,'Estenose pulmonar','Cardiovascular'),
(241,'Tetralogia de Fallot','Cardiovascular'),
(242,'Transposição das grandes artérias','Cardiovascular'),
(243,'Tronco arterial comum','Cardiovascular'),
(244,'Drenagem anômala das veias pulmonares','Cardiovascular'),
(245,'Atresia pulmonar','Cardiovascular'),
(246,'Atresia tricúspide','Cardiovascular'),
(247,'Anomalia de Ebstein','Cardiovascular'),
(248,'Síndrome do coração esquerdo hipoplásico','Cardiovascular'),
(249,'Ventrículo único','Cardiovascular'),
(250,'Dupla via de saída do ventrículo direito','Cardiovascular'),
(251,'Miocardite','Cardiovascular'),
(252,'Pericardite','Cardiovascular'),
(253,'Derrame pericárdico','Cardiovascular'),
(254,'Tamponamento cardíaco','Cardiovascular'),
(255,'Cardiomiopatias dilatada, hipertrófica ou restritiva','Cardiovascular'),
(256,'Doença cardíaca reumática','Cardiovascular'),
(257,'Comprometimento cardíaco na doença de Kawasaki','Cardiovascular'),
(258,'Disfunção cardíaca associada à sepse','Cardiovascular'),
(259,'Síndrome inflamatória multissistêmica pediátrica','Cardiovascular'),
(260,'Taquicardia supraventricular','Cardiovascular'),
(261,'Taquicardia ventricular','Cardiovascular'),
(262,'Fibrilação ventricular','Cardiovascular'),
(263,'Bradicardia sintomática','Cardiovascular'),
(264,'Bloqueios atrioventriculares','Cardiovascular'),
(265,'Síndrome do QT longo','Cardiovascular'),
(266,'Síndrome de Wolff-Parkinson-White','Cardiovascular'),
(267,'Insuficiência cardíaca aguda ou crônica','Cardiovascular'),
(268,'Crise hipóxica da tetralogia de Fallot','Cardiovascular'),
(269,'Crise de hipertensão pulmonar','Cardiovascular'),
(270,'Emergência hipertensiva','Cardiovascular'),
(271,'Trombose arterial ou venosa','Cardiovascular'),
(272,'Embolia pulmonar','Cardiovascular'),
(273,'Parada cardiorrespiratória','Cardiovascular'),
(274,'Síndrome pós-parada cardiorrespiratória','Cardiovascular'),
(275,'Síndrome de baixo débito cardíaco','Cardiovascular'),
(276,'Pós-operatório de cirurgia cardíaca pediátrica','Cardiovascular'),
(277,'Choque hipovolêmico','Choque / Distributivo'),
(278,'Choque distributivo/séptico','Choque / Distributivo'),
(279,'Choque cardiogênico','Choque / Distributivo'),
(280,'Choque obstrutivo','Choque / Distributivo'),
(281,'Choque anafilático','Choque / Distributivo'),
(282,'Choque neurogênico','Choque / Distributivo'),
(283,'Desnutrição aguda moderada ou grave','Nutricional / Outros'),
(284,'Desnutrição crônica','Nutricional / Outros'),
(285,'Baixo peso','Nutricional / Outros'),
(286,'Déficit de crescimento linear','Nutricional / Outros'),
(287,'Falha de crescimento','Nutricional / Outros'),
(288,'Caquexia associada à doença crônica','Nutricional / Outros'),
(289,'Sarcopenia pediátrica','Nutricional / Outros'),
(290,'Desnutrição hospitalar','Nutricional / Outros'),
(291,'Deficiência proteico-calórica','Nutricional / Outros'),
(292,'Deficiências de ferro, vitaminas A, D, B12, C e K, folato, zinco, tiamina, cobre ou selênio','Nutricional / Outros'),
(293,'Raquitismo nutricional','Nutricional / Outros'),
(294,'Sobrepeso','Nutricional / Outros'),
(295,'Obesidade','Nutricional / Outros'),
(296,'Obesidade grave','Nutricional / Outros'),
(297,'Síndrome metabólica','Nutricional / Outros'),
(298,'Resistência insulínica','Nutricional / Outros'),
(299,'Dislipidemia','Nutricional / Outros'),
(300,'Hipertensão relacionada à obesidade','Nutricional / Outros'),
(301,'Diabetes mellitus tipo 2','Nutricional / Outros'),
(302,'Obesidade sindrômica','Nutricional / Outros'),
(303,'Dificuldade alimentar pediátrica','Nutricional / Outros'),
(304,'Seletividade alimentar','Nutricional / Outros'),
(305,'Disfagia orofaríngea','Nutricional / Outros'),
(306,'Aversão alimentar','Nutricional / Outros'),
(307,'Transtorno alimentar restritivo/evitativo','Nutricional / Outros'),
(308,'Anorexia nervosa','Nutricional / Outros'),
(309,'Bulimia nervosa','Nutricional / Outros'),
(310,'Compulsão alimentar','Nutricional / Outros'),
(311,'Síndrome de realimentação','Nutricional / Outros'),
(312,'Intolerância à dieta enteral','Nutricional / Outros'),
(313,'Falência intestinal','Nutricional / Outros'),
(314,'Dependência de nutrição enteral ou parenteral','Nutricional / Outros'),
(315,'Complicações da nutrição parenteral','Nutricional / Outros'),
(316,'Distúrbios metabólicos associados à doença crítica','Nutricional / Outros'),
(317,'Meningite','Neurológico'),
(318,'Encefalite','Neurológico'),
(319,'Meningoencefalite','Neurológico'),
(320,'Empiema subdural','Neurológico'),
(321,'Encefalomielite disseminada aguda','Neurológico'),
(322,'Encefalite autoimune','Neurológico'),
(323,'Neuromielite óptica','Neurológico'),
(324,'Doença associada ao anticorpo anti-MOG','Neurológico'),
(325,'Esclerose múltipla pediátrica','Neurológico'),
(326,'Mielite transversa','Neurológico'),
(327,'Síndrome de Guillain-Barré','Neurológico'),
(328,'Crise convulsiva febril','Neurológico'),
(329,'Epilepsia','Neurológico'),
(330,'Síndromes epilépticas da infância','Neurológico'),
(331,'Estado de mal epiléptico','Neurológico'),
(332,'Estado de mal epiléptico refratário ou super-refratário','Neurológico'),
(333,'Espasmos infantis','Neurológico'),
(334,'Encefalopatia epiléptica','Neurológico'),
(335,'Coma','Neurológico'),
(336,'Encefalopatia aguda','Neurológico'),
(337,'Encefalopatia hipóxico-isquêmica','Neurológico'),
(338,'Morte encefálica','Neurológico'),
(339,'Atrofia muscular espinhal','Neurológico'),
(340,'Distrofia muscular de Duchenne','Neurológico'),
(341,'Miastenia gravis e crise miastênica','Neurológico'),
(342,'Miopatias congênitas','Neurológico'),
(343,'Doenças mitocondriais','Neurológico'),
(344,'Leucodistrofias','Neurológico'),
(345,'Botulismo','Neurológico'),
(346,'Paralisia flácida aguda','Neurológico'),
(347,'Hidrocefalia','Neurológico'),
(348,'Mielomeningocele','Neurológico'),
(349,'Malformação de Chiari','Neurológico'),
(350,'Paralisia cerebral','Neurológico'),
(351,'Atraso global ou regressão do desenvolvimento','Neurológico'),
(352,'Ataxia aguda','Neurológico'),
(353,'Cefaleia e enxaqueca','Neurológico'),
(354,'Acidente vascular cerebral isquêmico ou hemorrágico','Neurológico'),
(355,'Trombose venosa cerebral','Neurológico'),
(356,'Hemorragia intracraniana','Neurológico'),
(357,'Hipertensão intracraniana','Neurológico'),
(358,'Tumores do sistema nervoso central','Neurológico'),
(359,'Edema e herniação cerebral','Neurológico'),
(360,'Síndrome de disautonomia paroxística','Neurológico'),
(361,'TCE leve, moderado ou grave','Trauma / Cirúrgico'),
(362,'Concussão cerebral','Trauma / Cirúrgico'),
(363,'Contusão cerebral','Trauma / Cirúrgico'),
(364,'Lesão axonal difusa','Trauma / Cirúrgico'),
(365,'Hematoma epidural','Trauma / Cirúrgico'),
(366,'Hematoma subdural','Trauma / Cirúrgico'),
(367,'Hemorragia subaracnoidea traumática','Trauma / Cirúrgico'),
(368,'Hemorragia intraparenquimatosa','Trauma / Cirúrgico'),
(369,'Fratura de crânio','Trauma / Cirúrgico'),
(370,'Hipertensão intracraniana traumática','Trauma / Cirúrgico'),
(371,'Traumatismo craniano abusivo','Trauma / Cirúrgico'),
(372,'Contusão pulmonar','Trauma / Cirúrgico'),
(373,'Pneumotórax','Trauma / Cirúrgico'),
(374,'Hemotórax ou hemopneumotórax','Trauma / Cirúrgico'),
(375,'Tórax instável','Trauma / Cirúrgico'),
(376,'Lesão traqueobrônquica','Trauma / Cirúrgico'),
(377,'Contusão cardíaca','Trauma / Cirúrgico'),
(378,'Ruptura diafragmática','Trauma / Cirúrgico'),
(379,'Trauma hepático, esplênico, renal ou pancreático','Trauma / Cirúrgico'),
(380,'Perfuração de víscera oca','Trauma / Cirúrgico'),
(381,'Hemoperitônio','Trauma / Cirúrgico'),
(382,'Trauma pélvico','Trauma / Cirúrgico'),
(383,'Trauma de bexiga ou uretra','Trauma / Cirúrgico'),
(384,'Síndrome compartimental abdominal','Trauma / Cirúrgico'),
(385,'Fraturas fechadas ou expostas','Trauma / Cirúrgico'),
(386,'Luxações','Trauma / Cirúrgico'),
(387,'Lesões de partes moles','Trauma / Cirúrgico'),
(388,'Lesões vasculares ou nervosas','Trauma / Cirúrgico'),
(389,'Amputações traumáticas','Trauma / Cirúrgico'),
(390,'Síndrome compartimental','Trauma / Cirúrgico'),
(391,'Trauma raquimedular','Trauma / Cirúrgico'),
(392,'Politraumatismo','Trauma / Cirúrgico'),
(393,'Afogamento','Trauma / Cirúrgico'),
(394,'Queimaduras térmicas, químicas ou elétricas','Trauma / Cirúrgico'),
(395,'Choque elétrico','Trauma / Cirúrgico'),
(396,'Acidentes por animais peçonhentos','Trauma / Cirúrgico'),
(397,'Mordeduras','Trauma / Cirúrgico'),
(398,'Intoxicações exógenas','Trauma / Cirúrgico'),
(399,'Aspiração ou ingestão de corpo estranho','Trauma / Cirúrgico'),
(400,'Asfixia, estrangulamento ou sufocação','Trauma / Cirúrgico'),
(401,'Acidentes automobilísticos','Trauma / Cirúrgico'),
(402,'Quedas','Trauma / Cirúrgico'),
(403,'Violência física e trauma não acidental','Trauma / Cirúrgico'),
(404,'Atresia de esôfago e fístula traqueoesofágica','Trauma / Cirúrgico'),
(405,'Hérnia diafragmática congênita','Trauma / Cirúrgico'),
(406,'Gastrosquise','Trauma / Cirúrgico'),
(407,'Onfalocele','Trauma / Cirúrgico'),
(408,'Atresias intestinais','Trauma / Cirúrgico'),
(409,'Má rotação intestinal e volvo','Trauma / Cirúrgico'),
(410,'Enterocolite necrosante','Trauma / Cirúrgico'),
(411,'Perfuração intestinal','Trauma / Cirúrgico'),
(412,'Íleo meconial','Trauma / Cirúrgico'),
(413,'Doença de Hirschsprung','Trauma / Cirúrgico'),
(414,'Malformação anorretal','Trauma / Cirúrgico'),
(415,'Persistência do úraco','Trauma / Cirúrgico'),
(416,'Extrofia vesical','Trauma / Cirúrgico'),
(417,'Cisto de colédoco','Trauma / Cirúrgico'),
(418,'Apendicite aguda','Trauma / Cirúrgico'),
(419,'Peritonite','Trauma / Cirúrgico'),
(420,'Obstrução intestinal','Trauma / Cirúrgico'),
(421,'Volvo intestinal','Trauma / Cirúrgico'),
(422,'Aderências ou bridas intestinais','Trauma / Cirúrgico'),
(423,'Abscesso intra-abdominal','Trauma / Cirúrgico'),
(424,'Colecistite','Trauma / Cirúrgico'),
(425,'Pancreatite com complicação cirúrgica','Trauma / Cirúrgico'),
(426,'Hérnias inguinal e umbilical','Trauma / Cirúrgico'),
(427,'Hérnia encarcerada ou estrangulada','Trauma / Cirúrgico'),
(428,'Hidrocele','Trauma / Cirúrgico'),
(429,'Criptorquidia','Trauma / Cirúrgico'),
(430,'Torção testicular','Trauma / Cirúrgico'),
(431,'Fimose patológica e parafimose','Trauma / Cirúrgico'),
(432,'Hipospádia','Trauma / Cirúrgico'),
(433,'Varicocele','Trauma / Cirúrgico'),
(434,'Cisto ou torção ovariana','Trauma / Cirúrgico'),
(435,'Malformação congênita das vias aéreas pulmonares','Trauma / Cirúrgico'),
(436,'Sequestro pulmonar','Trauma / Cirúrgico'),
(437,'Cisto broncogênico','Trauma / Cirúrgico'),
(438,'Linfangioma e malformações vasculares','Trauma / Cirúrgico'),
(439,'Cisto tireoglosso','Trauma / Cirúrgico'),
(440,'Cisto branquial','Trauma / Cirúrgico'),
(441,'Neuroblastoma','Trauma / Cirúrgico'),
(442,'Tumor de Wilms','Trauma / Cirúrgico'),
(443,'Hepatoblastoma','Trauma / Cirúrgico'),
(444,'Teratomas','Trauma / Cirúrgico'),
(445,'Tumores ovarianos, testiculares ou de partes moles','Trauma / Cirúrgico'),
(446,'Hemorragia pós-operatória','Trauma / Cirúrgico'),
(447,'Infecção do sítio cirúrgico','Trauma / Cirúrgico'),
(448,'Deiscência de ferida ou anastomose','Trauma / Cirúrgico'),
(449,'Fístula digestiva','Trauma / Cirúrgico'),
(450,'Sepse abdominal','Trauma / Cirúrgico'),
(451,'Íleo paralítico','Trauma / Cirúrgico'),
(452,'Obstrução intestinal pós-operatória','Trauma / Cirúrgico'),
(453,'Complicações de estomias, drenos, gastrostomias e traqueostomias','Trauma / Cirúrgico'),
(454,'Transtorno do espectro autista','Psiquiátrico / Social'),
(455,'Transtorno do déficit de atenção e hiperatividade','Psiquiátrico / Social'),
(456,'Deficiência intelectual','Psiquiátrico / Social'),
(457,'Transtornos específicos da aprendizagem','Psiquiátrico / Social'),
(458,'Transtorno do desenvolvimento da linguagem','Psiquiátrico / Social'),
(459,'Transtorno do desenvolvimento da coordenação','Psiquiátrico / Social'),
(460,'Transtornos de tiques','Psiquiátrico / Social'),
(461,'Síndrome de Tourette','Psiquiátrico / Social'),
(462,'Transtorno depressivo','Psiquiátrico / Social'),
(463,'Transtorno bipolar','Psiquiátrico / Social'),
(464,'Transtorno de ansiedade generalizada','Psiquiátrico / Social'),
(465,'Ansiedade de separação','Psiquiátrico / Social'),
(466,'Fobia social e fobias específicas','Psiquiátrico / Social'),
(467,'Transtorno do pânico','Psiquiátrico / Social'),
(468,'Mutismo seletivo','Psiquiátrico / Social'),
(469,'Transtorno obsessivo-compulsivo','Psiquiátrico / Social'),
(470,'Transtorno de estresse pós-traumático','Psiquiátrico / Social'),
(471,'Transtorno opositor desafiante','Psiquiátrico / Social'),
(472,'Transtorno de conduta','Psiquiátrico / Social'),
(473,'Irritabilidade grave','Psiquiátrico / Social'),
(474,'Transtorno explosivo intermitente','Psiquiátrico / Social'),
(475,'Automutilação','Psiquiátrico / Social'),
(476,'Comportamento suicida','Psiquiátrico / Social'),
(477,'Transtorno de compulsão alimentar','Psiquiátrico / Social'),
(478,'Pica','Psiquiátrico / Social'),
(479,'Transtorno de ruminação','Psiquiátrico / Social'),
(480,'Primeiro episódio psicótico','Psiquiátrico / Social'),
(481,'Esquizofrenia de início precoce','Psiquiátrico / Social'),
(482,'Transtorno esquizoafetivo','Psiquiátrico / Social'),
(483,'Psicose induzida por substâncias ou medicamentos','Psiquiátrico / Social'),
(484,'Ideação ou tentativa de suicídio','Psiquiátrico / Social'),
(485,'Agitação psicomotora grave','Psiquiátrico / Social'),
(486,'Surto psicótico','Psiquiátrico / Social'),
(487,'Intoxicação ou abstinência de álcool e outras drogas','Psiquiátrico / Social'),
(488,'Delirium pediátrico','Psiquiátrico / Social'),
(489,'Síndrome de abstinência iatrogênica','Psiquiátrico / Social'),
(490,'Transtorno de adaptação à hospitalização','Psiquiátrico / Social'),
(491,'Catatonia','Psiquiátrico / Social'),
(492,'Transtornos somáticos e sintomas funcionais','Psiquiátrico / Social'),
(493,'Transtorno factício imposto a outro','Psiquiátrico / Social')
) AS v(n, label, categoria)
CROSS JOIN (
  SELECT DISTINCT ON (tipo) id, tipo, CASE tipo WHEN 'principal' THEN 'PRIN' ELSE 'SEC' END AS prefixo
  FROM public.perguntas_diagnistico
  WHERE tipo IN ('principal', 'secundario')
  ORDER BY tipo, id
) AS p
WHERE NOT EXISTS (
  SELECT 1 FROM public.pergunta_opcoes_diagnostico o
  WHERE o.pergunta_id = p.id AND o.label = v.label
);
