-- Criar tabela de medicamentos com categorias
CREATE TABLE public.medicamentos (
  id bigint generated by default as identity not null,
  categoria text not null,
  nome text not null,
  unidade_dose_principal text null, -- Ex: MG/KG/H, MG/KG/DIA, etc
  unidade_dose_secundaria text null, -- Ex: MG/KG/DIA (alternativa)
  criado_em timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint medicamentos_pkey primary key (id),
  constraint medicamentos_unique UNIQUE(categoria, nome)
) TABLESPACE pg_default;

-- Criar índices para performance
CREATE INDEX idx_medicamentos_categoria ON medicamentos(categoria);
CREATE INDEX idx_medicamentos_nome ON medicamentos(nome);

-- Inserir dados iniciais
INSERT INTO medicamentos (categoria, nome, unidade_dose_principal) VALUES
-- VASOATIVOS
('VASOATIVOS', 'Epinefrina', 'ug/kg/min'),
('VASOATIVOS', 'Noraepinefrina', 'ug/kg/min'),
('VASOATIVOS', 'Milrinona', 'ug/kg/min'),
('VASOATIVOS', 'Dobutamina', 'ug/kg/min'),
('VASOATIVOS', 'Vasopressina', 'UI/min'),
('VASOATIVOS', 'Nipride', 'ug/kg/min'),

-- SEDATIVOS E ANALGÉSICOS
('SEDATIVOS E ANALGÉSICOS', 'Midazolam', 'mg/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Fentanyl (Fentanila)', 'ug/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Morfina', 'mg/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Precedex (Dexmedetomidina)', 'ug/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Propofol', 'mg/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Clonidina', 'ug/kg/dia'),
('SEDATIVOS E ANALGÉSICOS', 'Cetamina', 'mg/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Tiopental', 'mg/kg/h'),
('SEDATIVOS E ANALGÉSICOS', 'Lorazepam', 'mg/kg'),
('SEDATIVOS E ANALGÉSICOS', 'Metadona', 'mg/kg/dia'),
('SEDATIVOS E ANALGÉSICOS', 'Diazepam', 'mg/kg'),

-- ANTICONVULSIVANTES
('ANTICONVULSIVANTES', 'Fenitoína', 'mg/kg'),
('ANTICONVULSIVANTES', 'Fenobarbital', 'mg/kg'),
('ANTICONVULSIVANTES', 'Topiramato', 'mg/kg/dia'),
('ANTICONVULSIVANTES', 'Levetiracetam', 'mg/kg/dia'),
('ANTICONVULSIVANTES', 'Ácido Valproico', 'mg/kg/dia'),
('ANTICONVULSIVANTES', 'Oxcarbazepina', 'mg/kg/dia'),

-- DIURÉTICOS
('DIURÉTICOS', 'Furosemida', 'mg/kg/dia'),
('DIURÉTICOS', 'Hidroclorotiazida', 'mg/kg/dia'),
('DIURÉTICOS', 'Espironolactona', 'mg/kg/dia'),
('DIURÉTICOS', 'Acetazolamida', 'mg/kg/dia'),

-- ELETRÓLITOS
('ELETRÓLITOS', 'Bicarbonato de Sódio', 'mEq/kg'),
('ELETRÓLITOS', 'Correção de Potássio', 'mEq/kg'),
('ELETRÓLITOS', 'Correção de Cálcio', 'mg/kg'),
('ELETRÓLITOS', 'Correção de Magnésio', 'mg/kg'),

-- CORTICOIDES
('CORTICOIDES', 'Hidrocortisona', 'mg/kg/dia'),
('CORTICOIDES', 'Metilprednisolona', 'mg/kg/dia'),
('CORTICOIDES', 'Dexametasona', 'mg/kg/dia'),

-- BRONCODILATADORES
('BRONCODILATADORES', 'Salbutamol injetável', 'ug/kg'),
('BRONCODILATADORES', 'Salbutamol spray', null),
('BRONCODILATADORES', 'Clenil Spray', null),
('BRONCODILATADORES', 'Terbutalina EV', 'ug/kg'),

-- ANTIBIÓTICOS
('ANTIBIÓTICOS', 'Amoxicilina', 'mg/kg/dia'),
('ANTIBIÓTICOS', 'Ceftriaxona', 'mg/kg/dia'),
('ANTIBIÓTICOS', 'Gentamicina', 'mg/kg/dia'),
('ANTIBIÓTICOS', 'Vancomicina', 'mg/kg/dia'),

-- SEM UNIDADE (medicamentos que não precisam de dosagem calculada)
('OUTROS', 'Octreotida', 'ug/kg/h'),
('OUTROS', 'Omeprazol', 'mg/kg/dia');

-- Alterar medicacoes_pacientes para aceitar unidade_medida nullable
ALTER TABLE public.medicacoes_pacientes 
ALTER COLUMN unidade_medida DROP NOT NULL;

-- Comentário no schema
COMMENT ON COLUMN public.medicamentos.unidade_dose_principal IS 'Unidade de dosagem padrão (ex: mg/kg/dia). Se NULL, medicação não requer dosagem';
COMMENT ON COLUMN public.medicacoes_pacientes.unidade_medida IS 'Unidade de medida (ex: mg/kg/dia). NULL se medicação não requer dosagem';
