-- ============================================================================
-- TABELA PRINCIPAL: BALANÇO HÍDRICO
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.balanco_hidrico (
  id bigint generated by default as identity not null,
  patient_id uuid not null,
  volume numeric(10, 2) not null,
  peso numeric(10, 2) not null,
  tipo text not null default 'Positivo', -- 'Positivo' ou 'Negativo' (entrada ou saída)
  resultado numeric GENERATED ALWAYS as (
    case
      when (peso > (0)::numeric) then (volume / (peso * 10.0))
      else (0)::numeric
    end
  ) STORED null,
  data_registro timestamp with time zone null default now(),
  created_at timestamp with time zone null default now(),
  created_by uuid,
  descricao text,
  constraint balanco_hidrico_pkey primary key (id),
  constraint fk_patient foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint fk_created_by foreign KEY (created_by) references users (id) on delete set null,
  constraint balanco_hidrico_peso_check check ((peso > (0)::numeric)),
  constraint balanco_hidrico_tipo_check check (tipo in ('Positivo', 'Negativo'))
) TABLESPACE pg_default;

-- ============================================================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_patient_id 
ON public.balanco_hidrico USING btree (patient_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_data_registro 
ON public.balanco_hidrico USING btree (data_registro DESC) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_patient_data 
ON public.balanco_hidrico (patient_id, data_registro DESC) TABLESPACE pg_default;

-- ============================================================================
-- VIEW: CÁLCULO DIÁRIO DO BALANÇO HÍDRICO
-- ============================================================================
CREATE OR REPLACE VIEW public.vw_balanco_diario AS
WITH calculo_diario AS (
    SELECT 
        patient_id,
        date_trunc('day', data_registro AT TIME ZONE 'America/Sao_Paulo') AS dia,
        -- Soma dos volumes considerando o tipo (Positivo/Negativo)
        SUM(CASE 
            WHEN tipo = 'Positivo' THEN volume 
            ELSE -volume 
        END) AS bh_do_dia,
        COUNT(*) AS total_registros
    FROM public.balanco_hidrico
    GROUP BY patient_id, date_trunc('day', data_registro AT TIME ZONE 'America/Sao_Paulo')
)
SELECT 
    patient_id,
    dia,
    bh_do_dia,
    LAG(bh_do_dia) OVER (PARTITION BY patient_id ORDER BY dia) AS bh_dia_anterior,
    SUM(bh_do_dia) OVER (PARTITION BY patient_id ORDER BY dia) AS bh_cumulativo,
    total_registros
FROM calculo_diario
ORDER BY patient_id, dia DESC;

-- ============================================================================
-- VIEW: RESUMO COMPLETO DO BALANÇO HÍDRICO
-- ============================================================================
CREATE OR REPLACE VIEW public.vw_resumo_balanco AS
WITH calculo_diario AS (
    SELECT 
        patient_id,
        date_trunc('day', data_registro AT TIME ZONE 'America/Sao_Paulo') AS dia,
        SUM(CASE 
            WHEN tipo = 'Positivo' THEN volume 
            ELSE -volume 
        END) AS bh_do_dia
    FROM public.balanco_hidrico
    GROUP BY patient_id, date_trunc('day', data_registro AT TIME ZONE 'America/Sao_Paulo')
)
SELECT 
    patient_id,
    dia,
    bh_do_dia,
    LAG(bh_do_dia) OVER (PARTITION BY patient_id ORDER BY dia) AS bh_dia_anterior,
    SUM(bh_do_dia) OVER (PARTITION BY patient_id ORDER BY dia) AS bh_cumulativo,
    -- Classificação do balanço
    CASE 
        WHEN bh_do_dia > 500 THEN 'Superávit Alto'
        WHEN bh_do_dia > 0 THEN 'Superávit'
        WHEN bh_do_dia = 0 THEN 'Equilibrado'
        WHEN bh_do_dia > -500 THEN 'Déficit'
        ELSE 'Déficit Alto'
    END AS classificacao
FROM calculo_diario
ORDER BY patient_id, dia DESC;

-- ============================================================================
-- VIEW: HISTÓRICO DETALHADO DO BALANÇO HÍDRICO COM NOMES DE USUÁRIOS
-- ============================================================================
CREATE OR REPLACE VIEW public.vw_balanco_historico_com_usuario AS
SELECT
    bh.id,
    bh.patient_id,
    bh.volume,
    bh.peso,
    bh.tipo,
    bh.resultado,
    (bh.data_registro AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo') AS data_registro,
    (bh.created_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo') AS data_criacao,
    bh.created_by,
    COALESCE(u.name, 'Sistema'::text) AS nome_criador,
    bh.descricao
FROM
    public.balanco_hidrico bh
LEFT JOIN public.users u ON bh.created_by = u.id
ORDER BY bh.patient_id, bh.data_registro DESC;

-- ============================================================================
-- GRANT DE PERMISSÕES (Se usando RLS)
-- ============================================================================
ALTER TABLE public.balanco_hidrico ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Usuários só veem dados do paciente da sua clínica
CREATE POLICY "balanco_hidrico_select_own_clinic" ON public.balanco_hidrico
FOR SELECT USING (
    patient_id IN (
        SELECT id FROM patients WHERE clinic_id IN (
            SELECT clinic_id FROM users WHERE id = auth.uid()
        )
    )
);

CREATE POLICY "balanco_hidrico_insert_own_clinic" ON public.balanco_hidrico
FOR INSERT WITH CHECK (
    patient_id IN (
        SELECT id FROM patients WHERE clinic_id IN (
            SELECT clinic_id FROM users WHERE id = auth.uid()
        )
    )
);

GRANT SELECT, INSERT, UPDATE ON public.balanco_hidrico TO authenticated;
GRANT SELECT ON public.vw_balanco_diario TO authenticated;
GRANT SELECT ON public.vw_resumo_balanco TO authenticated;
GRANT SELECT ON public.vw_balanco_historico_com_usuario TO authenticated;
