-- Create scale_scores table for storing clinical scale assessment results
create table public.scale_scores (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  scale_name text not null,
  score integer not null,
  interpretation text not null,
  date timestamp with time zone not null default now(),
  archived_at timestamp with time zone null,
  motivo_arquivamento text null,
  constraint scale_scores_pkey primary key (id),
  constraint scale_scores_patient_id_fkey foreign key (patient_id) references patients (id) on delete cascade
) tablespace pg_default;

-- Create index for faster queries by patient
create index scale_scores_patient_id_idx on public.scale_scores (patient_id);

-- Create index for faster queries by date
create index scale_scores_date_idx on public.scale_scores (date desc);

-- Create index for archived filtering
create index scale_scores_archived_idx on public.scale_scores (archived_at);
