-- Tabela para armazenar painéis moleculares/virais/sorológicos dos pacientes
CREATE TABLE IF NOT EXISTS public.paineis_virais_pacientes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  paciente_id uuid not null,
  categoria character varying(255) not null,
  painel character varying(500) not null,
  data_coleta date not null,
  resultado character varying(100) not null,
  valor text null,
  sistema character varying(255) null,
  observacao text null,
  created_by uuid null,
  archived_at timestamp with time zone null,
  motivo_arquivamento text null,
  constraint paineis_virais_pacientes_pkey primary key (id),
  constraint paineis_virais_pacientes_paciente_id_fkey foreign key (paciente_id) references patients (id) on delete cascade,
  constraint paineis_virais_pacientes_created_by_fkey foreign key (created_by) references auth.users (id)
) TABLESPACE pg_default;

-- Índices para melhor performance
CREATE INDEX idx_paineis_virais_paciente_id ON public.paineis_virais_pacientes(paciente_id);
CREATE INDEX idx_paineis_virais_created_at ON public.paineis_virais_pacientes(created_at);
CREATE INDEX idx_paineis_virais_data_coleta ON public.paineis_virais_pacientes(data_coleta);
CREATE INDEX idx_paineis_virais_archived_at ON public.paineis_virais_pacientes(archived_at);

-- RLS (Row Level Security)
ALTER TABLE public.paineis_virais_pacientes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view paineis of their own patients"
  ON public.paineis_virais_pacientes
  FOR SELECT
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

CREATE POLICY "Users can create paineis for their own patients"
  ON public.paineis_virais_pacientes
  FOR INSERT
  WITH CHECK (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

CREATE POLICY "Users can update paineis of their own patients"
  ON public.paineis_virais_pacientes
  FOR UPDATE
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

CREATE POLICY "Users can delete paineis of their own patients"
  ON public.paineis_virais_pacientes
  FOR DELETE
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );
