-- ================================================================
-- 📊 TABELA SCALE_SCORES
-- Armazena avaliações de escalas clínicas para pacientes
-- ================================================================

-- Criar tabela scale_scores
CREATE TABLE IF NOT EXISTS public.scale_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  patient_id UUID NOT NULL,
  scale_name TEXT NOT NULL,
  score INTEGER NOT NULL CHECK (score >= 0),
  interpretation TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by UUID,
  notes TEXT,
  CONSTRAINT scale_scores_pkey PRIMARY KEY (id),
  CONSTRAINT scale_scores_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients (id) ON DELETE CASCADE,
  CONSTRAINT scale_scores_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users (id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- ================================================================
-- ÍNDICES PARA PERFORMANCE
-- ================================================================

-- Índice para buscas por paciente
CREATE INDEX IF NOT EXISTS scale_scores_patient_id_idx ON public.scale_scores(patient_id);

-- Índice para buscas por nome da escala
CREATE INDEX IF NOT EXISTS scale_scores_scale_name_idx ON public.scale_scores(scale_name);

-- Índice composto para buscas por paciente e data
CREATE INDEX IF NOT EXISTS scale_scores_patient_date_idx ON public.scale_scores(patient_id, date DESC);

-- Índice para buscas recentes
CREATE INDEX IF NOT EXISTS scale_scores_created_at_idx ON public.scale_scores(created_at DESC);

-- ================================================================
-- ROW LEVEL SECURITY (RLS)
-- ================================================================

-- Habilitar RLS
ALTER TABLE public.scale_scores ENABLE ROW LEVEL SECURITY;

-- Política RLS: Usuários podem visualizar escalas de seus pacientes
CREATE POLICY "Users can view scale_scores from their patients"
  ON public.scale_scores
  FOR SELECT
  USING (
    patient_id IN (
      SELECT id FROM public.patients WHERE user_id = auth.uid()
    )
  );

-- Política RLS: Usuários podem inserir escalas para seus pacientes
CREATE POLICY "Users can insert scale_scores for their patients"
  ON public.scale_scores
  FOR INSERT
  WITH CHECK (
    patient_id IN (
      SELECT id FROM public.patients WHERE user_id = auth.uid()
    )
    AND created_by = auth.uid()
  );

-- Política RLS: Usuários podem atualizar escalas de seus pacientes
CREATE POLICY "Users can update scale_scores from their patients"
  ON public.scale_scores
  FOR UPDATE
  USING (
    patient_id IN (
      SELECT id FROM public.patients WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    patient_id IN (
      SELECT id FROM public.patients WHERE user_id = auth.uid()
    )
  );

-- Política RLS: Usuários podem deletar escalas de seus pacientes
CREATE POLICY "Users can delete scale_scores from their patients"
  ON public.scale_scores
  FOR DELETE
  USING (
    patient_id IN (
      SELECT id FROM public.patients WHERE user_id = auth.uid()
    )
  );

-- ================================================================
-- TRIGGERS PARA ATUALIZAÇÃO DE TIMESTAMP
-- ================================================================

-- Criar função para atualizar updated_at
CREATE OR REPLACE FUNCTION public.update_scale_scores_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Criar trigger para atualizar updated_at
DROP TRIGGER IF EXISTS scale_scores_updated_at_trigger ON public.scale_scores;
CREATE TRIGGER scale_scores_updated_at_trigger
  BEFORE UPDATE ON public.scale_scores
  FOR EACH ROW
  EXECUTE FUNCTION public.update_scale_scores_updated_at();

-- ================================================================
-- COMENTÁRIOS PARA DOCUMENTAÇÃO
-- ================================================================

COMMENT ON TABLE public.scale_scores IS 'Armazena avaliações de escalas clínicas para pacientes (FSS, Glasgow, BRADEN, etc.)';
COMMENT ON COLUMN public.scale_scores.id IS 'Identificador único da avaliação';
COMMENT ON COLUMN public.scale_scores.patient_id IS 'Referência ao paciente';
COMMENT ON COLUMN public.scale_scores.scale_name IS 'Nome da escala (ex: FSS, BRADEN, GLASGOW)';
COMMENT ON COLUMN public.scale_scores.score IS 'Pontuação obtida na avaliação';
COMMENT ON COLUMN public.scale_scores.interpretation IS 'Interpretação/classificação do resultado';
COMMENT ON COLUMN public.scale_scores.created_by IS 'Usuário que criou o registro';
COMMENT ON COLUMN public.scale_scores.notes IS 'Observações adicionais sobre a avaliação';
