-- Tabela para armazenar culturas microbiológicas dos pacientes
CREATE TABLE IF NOT EXISTS public.culturas_pacientes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  paciente_id uuid not null,
  local character varying(255) not null,
  microorganismo character varying(255) not null,
  data_coleta date not null,
  is_archived boolean null default false,
  observacao text null,
  constraint culturas_pacientes_pkey primary key (id),
  constraint culturas_pacientes_paciente_id_fkey foreign key (paciente_id) references patients (id) on delete cascade
) TABLESPACE pg_default;

-- Índices para melhor performance
CREATE INDEX idx_culturas_pacientes_paciente_id ON public.culturas_pacientes(paciente_id);
CREATE INDEX idx_culturas_pacientes_created_at ON public.culturas_pacientes(created_at);
CREATE INDEX idx_culturas_pacientes_data_coleta ON public.culturas_pacientes(data_coleta);

-- RLS (Row Level Security) - Restriciona acesso aos pacientes do usuário
ALTER TABLE public.culturas_pacientes ENABLE ROW LEVEL SECURITY;

-- Policy: Usuários podem visualizar culturas de seus próprios pacientes
CREATE POLICY "Users can view cultures of their own patients"
  ON public.culturas_pacientes
  FOR SELECT
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

-- Policy: Usuários podem criar culturas para seus pacientes
CREATE POLICY "Users can create cultures for their own patients"
  ON public.culturas_pacientes
  FOR INSERT
  WITH CHECK (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

-- Policy: Usuários podem atualizar culturas de seus pacientes
CREATE POLICY "Users can update cultures of their own patients"
  ON public.culturas_pacientes
  FOR UPDATE
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

-- Policy: Usuários podem deletar culturas de seus pacientes
CREATE POLICY "Users can delete cultures of their own patients"
  ON public.culturas_pacientes
  FOR DELETE
  USING (
    paciente_id IN (
      SELECT id FROM patients WHERE created_by = auth.uid()
    )
  );

-- Trigger para atualizar updated_at (opcional - se necessário)
CREATE OR REPLACE FUNCTION update_culturas_pacientes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Nota: Se a tabela não tiver coluna updated_at, comente a trigger acima
-- CREATE TRIGGER trigger_culturas_pacientes_updated_at
--   BEFORE UPDATE ON public.culturas_pacientes
--   FOR EACH ROW
--   EXECUTE FUNCTION update_culturas_pacientes_updated_at();
