create table public.diurese (
  id bigint generated by default as identity not null,
  patient_id uuid not null,
  volume numeric(10, 2) not null,
  peso numeric(10, 2) not null,
  horas integer not null,
  resultado numeric GENERATED ALWAYS as (
    case
      when (
        (peso > (0)::numeric)
        and (horas > 0)
      ) then ((volume / (horas)::numeric) / peso)
      else (0)::numeric
    end
  ) STORED null,
  data_registro timestamp with time zone null default now(),
  constraint diurese_pkey primary key (id),
  constraint fk_patient foreign KEY (patient_id) references patients (id) on delete CASCADE
) TABLESPACE pg_default;