-- Criar tabela scale_scores para armazenar avaliações das escalas clínicas
create table public.scale_scores (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  patient_id uuid not null,
  scale_name text not null,
  score integer not null,
  interpretation text not null,
  date timestamp with time zone not null default now(),
  constraint scale_scores_pkey primary key (id),
  constraint scale_scores_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE
) TABLESPACE pg_default;

-- Criar índice para melhor performance nas buscas por paciente
create index scale_scores_patient_id_idx on public.scale_scores(patient_id);

-- Criar índice para melhor performance nas buscas por nome da escala
create index scale_scores_scale_name_idx on public.scale_scores(scale_name);

-- Criar índice composto para buscas por paciente e data
create index scale_scores_patient_date_idx on public.scale_scores(patient_id, date desc);

-- Habilitar RLS (Row Level Security)
alter table public.scale_scores enable row level security;

-- Política RLS: Usuários podem visualizar escalas de seus pacientes
create policy "Users can view scale_scores from their patients"
  on public.scale_scores
  for select
  using (
    patient_id in (
      select id from patients where user_id = auth.uid()
    )
  );

-- Política RLS: Usuários podem inserir escalas para seus pacientes
create policy "Users can insert scale_scores for their patients"
  on public.scale_scores
  for insert
  with check (
    patient_id in (
      select id from patients where user_id = auth.uid()
    )
  );

-- Política RLS: Usuários podem atualizar escalas de seus pacientes
create policy "Users can update scale_scores from their patients"
  on public.scale_scores
  for update
  using (
    patient_id in (
      select id from patients where user_id = auth.uid()
    )
  );

-- Política RLS: Usuários podem deletar escalas de seus pacientes
create policy "Users can delete scale_scores from their patients"
  on public.scale_scores
  for delete
  using (
    patient_id in (
      select id from patients where user_id = auth.uid()
    )
  );
