-- Create diagnosticos_historico_com_usuario view
DROP VIEW IF EXISTS public.diagnosticos_historico_com_usuario CASCADE;

CREATE VIEW public.diagnosticos_historico_com_usuario AS
SELECT
  dh.id,
  dh.patient_id,
  dh.pergunta_id,
  dh.opcao_id,
  dh.texto_digitado,
  dh.status,
  dh.created_at,
  dh.opcao_label,
  dh.created_by,
  COALESCE(u.name, 'Sistema'::text) AS created_by_name
FROM
  diagnosticos_historico dh
  LEFT JOIN users u ON dh.created_by = u.id
ORDER BY
  dh.created_at DESC;

-- Create balanco_hidrico table
CREATE TABLE IF NOT EXISTS public.balanco_hidrico (
  id bigint generated by default as identity not null,
  patient_id uuid not null,
  volume numeric(10, 2) not null,
  peso numeric(10, 2) not null,
  resultado numeric GENERATED ALWAYS as (
    case
      when (peso > (0)::numeric) then (volume / (peso * 10.0))
      else (0)::numeric
    end
  ) STORED null,
  data_registro timestamp with time zone null default now(),
  created_at timestamp with time zone null default now(),
  constraint balanco_hidrico_pkey primary key (id),
  constraint fk_patient foreign KEY (patient_id) references patients (id) on delete CASCADE,
  constraint balanco_hidrico_peso_check check ((peso > (0)::numeric))
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_patient_id ON public.balanco_hidrico USING btree (patient_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_data_registro ON public.balanco_hidrico USING btree (data_registro desc) TABLESPACE pg_default;

-- Create balanco_hidrico_historico table
CREATE TABLE IF NOT EXISTS public.balanco_hidrico_historico (
  id uuid not null default gen_random_uuid (),
  patient_id uuid not null,
  peso numeric(10, 2) not null,
  volume numeric(10, 2) not null,
  resultado numeric(10, 4) not null,
  data_calculo timestamp without time zone null default CURRENT_TIMESTAMP,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint balanco_hidrico_historico_pkey primary key (id),
  constraint balanco_hidrico_historico_patient_id_fkey foreign KEY (patient_id) references patients (id) on delete CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_historico_patient_id ON public.balanco_hidrico_historico USING btree (patient_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_historico_data_calculo ON public.balanco_hidrico_historico USING btree (data_calculo desc) TABLESPACE pg_default;

-- Enable RLS if needed
ALTER TABLE public.balanco_hidrico ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balanco_hidrico_historico ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY balanco_hidrico_select_policy ON public.balanco_hidrico
  FOR SELECT USING (true);

CREATE POLICY balanco_hidrico_insert_policy ON public.balanco_hidrico
  FOR INSERT WITH CHECK (true);

CREATE POLICY balanco_hidrico_historico_select_policy ON public.balanco_hidrico_historico
  FOR SELECT USING (true);

CREATE POLICY balanco_hidrico_historico_insert_policy ON public.balanco_hidrico_historico
  FOR INSERT WITH CHECK (true);
